-- Display Oracle database version information
SELECT * FROM v$version;

-- Display the current user
SELECT USER FROM DUAL;

-- To fetch total available tables owned by current user / the user executing the query.
SELECT * FROM USER_TABLES;

-- To fetch total available tables that are accessible to the current user, including tables owned by other users.
SELECT * FROM all_tables;

-- Retrieve the 'created_by' specific column from the "teamdetails" table
SELECT created_by FROM teamdetails;

-- Uncommented SELECT query with schema prefix
select * from UMSUSER.teamdetails;

-- SELECT query from "Teamdetails"
SELECT * FROM teamdetails;
SELECT * FROM positiondetails;
SELECT * FROM regiondetails;
SELECT * FROM user_hierarchy_details;

-- To view tables structure
DESC UMSUSER.POSITIONDETAILS;
DESC UMSUSER.user_hierarchy_details;

-- Select the table name for "teamdetails" from USER_TABLES
SELECT table_name FROM USER_TABLES WHERE table_name = 'teamdetails';

-- Insert data
-- Uncommented INSERT query for "teamdetails" table
-- insert into "teamdetails" ("name", "is_active", "parent_id", "department", "is_leaf", "created_by", "updated_by", "updated_by_name", "created_by_name") 
-- values ('ums-team-dev", 1, 0, 'Dev', 0, 'testuser', 'testuser1', 'testuser User', 'testuser User');

-- Uncommented INSERT query for "teamdetails" table with modified values
-- insert into "teamdetails" ("name", "is_active", "parent_id", "department", "is_leaf", "created_date", "updated_date","created_by","updated_by") 
-- values ('ums-team-dev', 1, 0, 'Development', 0, 'testuser', 'testuser1', 'testuser User', 'testuser User');

-- INSERT query for "teamdetails" table with simplified values
INSERT INTO teamdetails (name, is_active, parent_id, department, is_leaf, created_by, updated_by) 
VALUES ('ums-team-dev-1', 1, 0, 'Development', 0, 'testuser1', 'testuser1');

-- Rename the "parent_id" column in "TEAMDETAILS" table
alter table TEAMDETAILS rename column "parent_id" to PARENT_ID;

-- Modify Existing column constraints
-- Modify the existing ID column to support auto-increment in teamDetails table

-- Uncommented ALTER TABLE query (to modify column name ----> method1)
-- ALTER TABLE TEAMDETAILS MODIFY (id NUMBER GENERATED ALWAYS AS IDENTITY);
-- ALTER TABLE TEAMDETAILS MODIFY (ID NUMBER GENERATED BY DEFAULT AS IDENTITY);
-- ALTER TABLE UMSUSER.POSITIONDETAILS MODIFY (ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);

-- Uncommented DROP CONSTRAINT query(to modify column name --> method2)
-- ALTER TABLE UMSUSER.TEAMDETAILS DROP CONSTRAINT teamdetails_PK;

-- Drop the "Id" column from "TEAMDETAILS" table
--ALTER TABLE UMSUSER.TEAMDETAILS DROP COLUMN Id;
--ALTER TABLE UMSUSER.POSITIONDETAILS DROP COLUMN Id;
--ALTER TABLE UMSUSER.user_hierarchy_details DROP COLUMN Id;

-- Add a new auto-incremented "id" column as the primary key
ALTER TABLE UMSUSER.TEAMDETAILS ADD id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE UMSUSER.POSITIONDETAILS ADD id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE UMSUSER.user_hierarchy_details ADD id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- Select query to retrieve data from "teamdetails" table
select teamdetail0_.id as id1_0_, teamdetail0_.created_by as created_by2_0_, teamdetail0_.created_date as created_date3_0_, teamdetail0_.is_active as is_active4_0_, teamdetail0_.is_leaf as is_leaf5_0_, teamdetail0_.name as name6_0_, teamdetail0_.parent_id as parent_id7_0_, teamdetail0_.updated_by as updated_by8_0_, teamdetail0_.updated_date as updated_date9_0_ 
from UMSUSER.teamdetails teamdetail0_ 
where teamdetail0_.is_active=1 and teamdetail0_.is_active=1 and teamdetail0_.is_active=1 
order by teamdetail0_.updated_date desc;

-- DELETE all records from "UMSUSER.TEAMDETAILS" table
DELETE FROM UMSUSER.TEAMDETAILS;

-- Select query with repeated conditions
select * from "teamdetails" teamdetail0_ 
where teamdetail0_."is_active"=1 
and teamdetail0_."is_active"=1 
and teamdetail0_."is_active"=1 
order by teamdetail0_."updated_date" desc;

-- Select query with a row limit
select * from 
( 
    select teamdetail0_."id" as id1_0_, teamdetail0_."created_by" as created_by2_0_, teamdetail0_."created_date" as created_date3_0_, teamdetail0_."is_active" as is_active4_0_, teamdetail0_."is_leaf" as is_leaf5_0_, teamdetail0_."name" as name6_0_, teamdetail0_."parent_id" as parent_id7_0_, teamdetail0_."updated_by" as updated_by8_0_, teamdetail0_."updated_date" as updated_date9_0_ 
    from "teamdetails" teamdetail0_ 
    where teamdetail0_."is_active"=1 
    and teamdetail0_."is_active"=1 
    and teamdetail0_."is_active"=1 
    order by teamdetail0_."updated_date" desc 
) 
where rownum <= ?;

-- Additional comments and queries can be added here
