SELECT * FROM v$version;

-- creating new user
CREATE USER umsuser IDENTIFIED BY umsuser;

ALTER USER umsuser QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO umsuser;

COMMIT;

--check created users
SELECT * FROM all_users;
SELECT * FROM all_users WHERE username = 'UMSUSER';

---Create New conncetion & give above user deatails;

---Shift to that new connections to execute sql scripts by going to conncetions dropdown towards bottom right

---To check current connected user
SELECT USER FROM DUAL;

--list tables for the currently connected user
SELECT * FROM USER_TABLES;

--list all tables regardless of the connected user
SELECT * FROM all_tables;

--list tables for a specific user
SELECT table_name, owner FROM all_tables WHERE owner = 'UMSUSER'; 

--ALL_TABLES: Shows all tables in the database accessible to the current user.
--DBA_TABLES: Shows all tables in the entire database.
--USER_TABLES: Shows tables owned by the current user.

--Create table

CREATE TABLE teamdetails (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name VARCHAR2(50 CHAR) NOT NULL,
  is_active NUMBER(1, 0) DEFAULT 0,
  parent_id NUMBER DEFAULT 0,
  department VARCHAR2(50 CHAR),
  is_leaf NUMBER DEFAULT 0,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR2(40 CHAR),
  updated_by VARCHAR2(40 CHAR),
  updated_by_name VARCHAR2(40 CHAR),
  created_by_name VARCHAR2(40 CHAR),
  PRIMARY KEY (id)
);

-- view the table data
SELECT * FROM UMSUSER.TEAMDETAILS;
SELECT * FROM TEAMDETAILS;

---Insert data
INSERT INTO UMSUSER.TEAMDETAILS (NAME, IS_ACTIVE, PARENT_ID, DEPARTMENT, IS_LEAF, CREATED_BY, UPDATED_BY, UPDATED_BY_NAME, CREATED_BY_NAME) 
VALUES ('Development Team', 1, 0, 'Engineering', 0, 'testuser', 'testuser1', 'testuser User', 'testuser User');
--  ('Testing Team', 1, 0, 'Quality Assurance', 0, 'Admin', 'Admin', 'Admin User', 'Admin User');

--view table
select
    teamdetail0_.id as id1_0_,
            teamdetail0_.created_by as created_by2_0_,
            teamdetail0_.created_date as created_date3_0_,
            teamdetail0_.is_active as is_active4_0_,
            teamdetail0_.is_leaf as is_leaf5_0_,
            teamdetail0_.name as name6_0_,
            teamdetail0_.parent_id as parent_id7_0_,
            teamdetail0_.updated_by as updated_by8_0_,
            teamdetail0_.updated_date as updated_date9_0_
        from
            TEAMDETAILS teamdetail0_
        where
            teamdetail0_.is_active=1
            and teamdetail0_.is_active=1
            and teamdetail0_.is_active=1
        order by
            teamdetail0_.updated_date desc ;
            

SELECT table_name
FROM user_tables;

SELECT table_name, owner
FROM all_tables;

SELECT table_name FROM all_tables WHERE table_name = 'MYTABLE';
INSERT INTO MYTABLE (ID, NAME) VALUES (1, 'John');

select * from MYTABLE;



